import type { ComplianceItem, GrantMatch, Business } from "@/lib/types";

export const MOCK_BUSINESS: Business = {
  id: "demo-business-1",
  name: "Warung Mak Jah",
  type: "fnb",
  location: "Subang Jaya",
  state: "Selangor",
  council: "MBPJ",
  employees: 3,
  channels: ["offline", "online"],
  product_type: "halal food",
  raw_prompt: "Saya jual nasi lemak kat Subang, ada 3 pekerja, jual online jugak...",
  owner_email: "demo@warungmakjah.my",
  language_pref: "bm",
  phone: "+60123456789",
};

export const MOCK_ITEMS: ComplianceItem[] = [
  {
    id: "item-1",
    business_id: MOCK_BUSINESS.id,
    name: "SSM Business Registration",
    authority: "SSM",
    deadline: "2026-11-01",
    renewal_cycle: "annual",
    status: "compliant",
    risk_score: 25,
    priority: "CRITICAL",
    penalty_rm_min: 50000,
    penalty_rm_max: 50000,
    notes: null,
    document_uploaded: true,
    expiry_date: "2026-11-01",
  },
  {
    id: "item-2",
    business_id: MOCK_BUSINESS.id,
    name: "SST Registration & Filing",
    authority: "LHDN",
    deadline: "2026-05-01",
    renewal_cycle: "bimonthly",
    status: "missing",
    risk_score: 100,
    priority: "HIGH",
    penalty_rm_min: 10000,
    penalty_rm_max: 50000,
    notes: null,
    document_uploaded: false,
    expiry_date: null,
  },
  {
    id: "item-3",
    business_id: MOCK_BUSINESS.id,
    name: "JAKIM Halal Certification",
    authority: "JAKIM",
    deadline: "2026-09-30",
    renewal_cycle: "2 years",
    status: "missing",
    risk_score: 100,
    priority: "HIGH",
    penalty_rm_min: 0,
    penalty_rm_max: 0,
    notes: null,
    document_uploaded: false,
    expiry_date: null,
  },
  {
    id: "item-4",
    business_id: MOCK_BUSINESS.id,
    name: "Premises Business Licence",
    authority: "Local Council",
    deadline: "2026-05-02",
    renewal_cycle: "annual",
    status: "expiring_soon",
    risk_score: 80,
    priority: "HIGH",
    penalty_rm_min: 2000,
    penalty_rm_max: 10000,
    notes: null,
    document_uploaded: true,
    expiry_date: "2026-05-02",
  },
  {
    id: "item-5",
    business_id: MOCK_BUSINESS.id,
    name: "Signboard Permit",
    authority: "Local Council",
    deadline: "2026-07-01",
    renewal_cycle: "annual",
    status: "missing",
    risk_score: 100,
    priority: "MEDIUM",
    penalty_rm_min: 500,
    penalty_rm_max: 2000,
    notes: null,
    document_uploaded: false,
    expiry_date: null,
  },
  {
    id: "item-6",
    business_id: MOCK_BUSINESS.id,
    name: "EPF + SOCSO Monthly",
    authority: "KWSP/PERKESO",
    deadline: "2026-04-15",
    renewal_cycle: "monthly",
    status: "pending",
    risk_score: 50,
    priority: "HIGH",
    penalty_rm_min: 200,
    penalty_rm_max: 2000,
    notes: null,
    document_uploaded: true,
    expiry_date: "2026-04-15",
  },
  {
    id: "item-7",
    business_id: MOCK_BUSINESS.id,
    name: "MDEC e-Commerce Reg",
    authority: "MDEC",
    deadline: "2027-01-01",
    renewal_cycle: "one-time",
    status: "missing",
    risk_score: 100,
    priority: "MEDIUM",
    penalty_rm_min: 0,
    penalty_rm_max: 0,
    notes: null,
    document_uploaded: false,
    expiry_date: null,
  },
];

export const MOCK_GRANTS: GrantMatch[] = [
  {
    grant_name: "SME Digitalisation Grant",
    grant_body: "MDEC",
    value_rm: 5000,
    eligibility_pct: 92,
    apply_url: "https://mdec.my/",
  },
];

export function mockRiskPayload() {
  return {
    overall_score: 72,
    penalty_exposure: 72000,
    items: MOCK_ITEMS,
    forecast: [
      { name: "JAKIM Halal Certification", days_until_flip: 34, projected_risk: 95, milestone: "T+30" },
      { name: "SST Registration & Filing", days_until_flip: 50, projected_risk: 95, milestone: "T+60" },
    ],
  };
}